export const projects = [
  {
    id: "adventureseek",
    title: "AdventureSeek",
    description:
      "A comprehensive travel planning and booking platform. Features interactive maps, real-time availability, and personalized trip recommendations.",
    longDescription: `AdventureSeek revolutionizes travel planning by combining AI-driven personalization with real-time booking capabilities. The platform uses advanced machine learning algorithms to analyze user preferences, travel history, and global trends to deliver highly personalized trip recommendations.
  
      The system features a sophisticated real-time availability engine that integrates with multiple travel service providers, ensuring accurate and up-to-date booking information. The interactive mapping system combines satellite imagery with user-generated content to provide immersive location previews and route planning.`,
    category: "Web Development",
    date: "January 12, 2024",
    image: "/images/project/Adventureseek.png",
    github: "https://github.com/yourusername/adventureseek",
    demo: "https://adventureseek.vercel.app",
    tech: [
      "Next.js",
      "React",
      "Node.js",
      "MongoDB",
      "TensorFlow.js",
      "MapboxGL",
      "Redis",
      "WebSocket",
    ],
    features: [
      "AI-Powered Trip Recommendations",
      "Real-time Availability Tracking",
      "Interactive 3D Maps",
      "Dynamic Price Prediction",
      "Social Planning Tools",
      "Offline Access Support",
    ],
    challenges: [
      "Handling complex real-time booking synchronization",
      "Implementing efficient caching for map data",
      "Optimizing AI recommendations for speed",
      "Managing concurrent booking requests",
      "Ensuring cross-platform compatibility",
    ],
    solutions: [
      "Implemented WebSocket for real-time updates",
      "Developed custom caching algorithm",
      "Built hybrid AI processing system",
      "Created distributed booking queue",
      "Used progressive enhancement",
    ],
    metrics: [
      { label: "User Satisfaction", value: "94%" },
      { label: "Booking Success", value: "99.9%" },
      { label: "Load Time", value: "1.2s" },
      { label: "Active Users", value: "50k+" },
    ],
    teamSize: "4 developers",
    duration: "6 months",
    nextSteps: [
      "Mobile App Development",
      "AI Enhancement",
      "VR Location Preview",
      "Local Guide Integration",
    ],
  },
  {
    id: "arcaureus-autonav",
    title: "Arcaureus AutoNav",
    description:
      "Autonomous navigation system with advanced path planning and obstacle avoidance capabilities. Integrates with various robotic platforms.",
    longDescription: `Arcaureus AutoNav represents a breakthrough in autonomous navigation technology, combining sophisticated path planning algorithms with real-time obstacle avoidance systems. The platform utilizes cutting-edge SLAM (Simultaneous Localization and Mapping) techniques and deep learning models for environmental understanding.
  
      The system processes data from multiple sensor types including LiDAR, cameras, and ultrasonic sensors, creating a comprehensive environmental awareness system. Its modular architecture allows for easy integration with various robotic platforms, from industrial automation to service robots.`,
    category: "Robotics",
    date: "January 10, 2024",
    image: "/images/project/Arcaureus_Autonav.png",
    github: "https://github.com/yourusername/arcaureus-autonav",
    demo: "https://autonav.arcaureus.com",
    tech: [
      "ROS",
      "Python",
      "C++",
      "Computer Vision",
      "TensorFlow",
      "CUDA",
      "OpenCV",
      "PCL",
    ],
    features: [
      "Dynamic Path Planning",
      "Real-time Obstacle Avoidance",
      "Multi-sensor Fusion",
      "Adaptive Speed Control",
      "Environmental Mapping",
      "Remote Monitoring Interface",
    ],
    challenges: [
      "Processing high-volume sensor data in real-time",
      "Ensuring reliable operation in dynamic environments",
      "Minimizing latency in decision-making",
      "Managing power consumption",
      "Handling edge cases in navigation",
    ],
    solutions: [
      "Implemented GPU acceleration",
      "Developed hybrid processing pipeline",
      "Created optimized algorithm stack",
      "Built power management system",
      "Extensive edge case testing",
    ],
    metrics: [
      { label: "Navigation Accuracy", value: "99.7%" },
      { label: "Response Time", value: "5ms" },
      { label: "Battery Life", value: "12h" },
      { label: "Success Rate", value: "98%" },
    ],
    teamSize: "3 developers",
    duration: "4 months",
    nextSteps: [
      "Multi-robot Coordination",
      "Advanced Terrain Handling",
      "Cloud Integration",
      "Battery Optimization",
    ],
  },
  {
    id: "arcaureus-hub",
    title: "Arcaureus Hub",
    description:
      "AI-driven, scalable smart home solution featuring advanced device integration, real-time health monitoring, and privacy-first local processing.",
    longDescription: `Arcaureus Hub transforms the smart home experience by prioritizing privacy and local processing while delivering sophisticated automation and monitoring capabilities. The system uses edge computing to process sensitive data locally, ensuring user privacy while maintaining responsive performance.
  
      The platform features a neural network-based learning system that adapts to user patterns and preferences, creating a truly personalized home automation experience. The health monitoring system integrates with various IoT devices to provide comprehensive wellness tracking and emergency alerts.`,
    category: "IoT",
    date: "January 8, 2024",
    image: "/images/project/Arcaureus_Hub.png",
    github: "https://github.com/yourusername/arcaureus-hub",
    demo: "https://hub.arcaureus.com",
    tech: [
      "React",
      "Node.js",
      "TensorFlow.js",
      "WebSocket",
      "MQTT",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
    ],
    features: [
      "Edge Computing Architecture",
      "Real-time Health Monitoring",
      "Privacy-First Processing",
      "Predictive Maintenance",
      "Energy Optimization",
      "Emergency Response System",
    ],
    challenges: [
      "Ensuring data privacy while maintaining functionality",
      "Managing multiple device protocols",
      "Optimizing edge processing",
      "Handling offline scenarios",
      "Scaling device management",
    ],
    solutions: [
      "Implemented local-first architecture",
      "Created protocol abstraction layer",
      "Optimized edge computing pipeline",
      "Developed offline-first approach",
      "Built scalable device management",
    ],
    metrics: [
      { label: "Response Time", value: "<50ms" },
      { label: "Uptime", value: "99.99%" },
      { label: "Privacy Score", value: "100%" },
      { label: "Energy Saved", value: "35%" },
    ],
    teamSize: "Solo project",
    duration: "3 months",
    nextSteps: [
      "Enhanced AI Capabilities",
      "Extended Device Support",
      "Advanced Analytics",
      "Mobile App Enhancement",
    ],
  },
  {
    id: "arcaureus-stream",
    title: "Arcaureus Stream",
    description:
      "Next-generation AI-powered entertainment platform featuring CineAI assistant, advanced content recommendations, and sophisticated natural language processing.",
    longDescription: `Arcaureus Stream redefines digital entertainment by incorporating advanced AI technologies to deliver a highly personalized streaming experience. The platform's CineAI assistant understands complex queries about content, actors, and themes, providing intelligent recommendations and insights.
  
      The system features sophisticated content analysis that goes beyond traditional metadata, understanding themes, visual elements, and narrative structures to provide more accurate recommendations. The natural language processing system can handle complex queries and conversation-like interactions.`,
    category: "Streaming",
    date: "January 5, 2024",
    image: "/images/project/Arcaureus_Stream.png",
    github: "#",
    demo: "#",
    tech: [
      "Next.js 14",
      "OpenAI GPT-4",
      "Firebase",
      "TypeScript",
      "Framer Motion",
      "FFmpeg",
      "Redis",
      "ElasticSearch",
    ],
    features: [
      "Conversational AI Assistant",
      "Deep Content Analysis",
      "Personalized Recommendations",
      "Cross-Platform Sync",
      "Social Watching Features",
      "Advanced Content Discovery",
    ],
    challenges: [
      "Processing large media datasets",
      "Maintaining low latency",
      "Handling complex user queries",
      "Scaling recommendation system",
      "Managing streaming quality",
    ],
    solutions: [
      "Implemented distributed processing",
      "Created caching system",
      "Developed NLP pipeline",
      "Built scalable recommendation engine",
      "Adaptive streaming solution",
    ],
    metrics: [
      { label: "User Retention", value: "92%" },
      { label: "Response Time", value: "200ms" },
      { label: "Accuracy", value: "96%" },
      { label: "Engagement", value: "+45%" },
    ],
    teamSize: "2 developers",
    duration: "5 months",
    nextSteps: [
      "Enhanced AI Features",
      "Live Content Integration",
      "Social Features Expansion",
      "Mobile App Development",
    ],
  },
  {
    id: "astroexture",
    title: "AstroExture",
    description:
      "AI-powered web development platform that revolutionizes website creation with intelligent design recommendations and customization capabilities.",
    longDescription: `AstroExture transforms website creation through AI-driven design intelligence and advanced customization tools. The platform analyzes design trends, user behavior, and conversion metrics to provide data-driven design recommendations while maintaining creative flexibility.
  
      The system includes a sophisticated component library that adapts to brand guidelines and user preferences, ensuring consistent design language across projects. The AI system learns from user interactions and successful websites to continuously improve its recommendations.`,
    category: "Web Development",
    date: "January 3, 2024",
    image: "/images/project/Astroexture.jpg",
    github: "#",
    demo: "#",
    tech: [
      "Next.js",
      "TensorFlow.js",
      "Three.js",
      "Node.js",
      "MongoDB",
      "WebGL",
      "GraphQL",
      "Redis",
    ],
    features: [
      "AI Design Assistant",
      "Real-time Customization",
      "Component Generation",
      "Performance Analytics",
      "SEO Optimization",
      "Code Generation",
    ],
    challenges: [
      "Balancing automation with customization",
      "Ensuring generated code quality",
      "Managing design consistency",
      "Handling complex interactions",
      "Optimizing performance",
    ],
    solutions: [
      "Created hybrid design system",
      "Implemented code validation",
      "Developed design token system",
      "Built interaction manager",
      "Optimized rendering pipeline",
    ],
    metrics: [
      { label: "Design Time", value: "-65%" },
      { label: "Code Quality", value: "98%" },
      { label: "User Satisfaction", value: "91%" },
      { label: "Performance", value: "95/100" },
    ],
    teamSize: "2 developers",
    duration: "4 months",
    nextSteps: [
      "Advanced AI Features",
      "Template Marketplace",
      "Plugin System",
      "Collaboration Tools",
    ],
  },
  {
    id: "lmdx-healthcare",
    title: "LMDX Healthcare",
    description:
      "Next-generation healthcare platform integrating advanced AI technologies for predictive analytics and sophisticated medical image analysis.",
    longDescription: `LMDX Healthcare revolutionizes medical care through advanced AI integration and comprehensive patient data analysis. The platform combines medical imaging analysis, predictive analytics, and patient management into a unified healthcare solution.
  
      The system features sophisticated machine learning models for medical image analysis, helping identify potential issues early. The predictive analytics engine processes patient history and current health data to provide early warning of potential health issues and treatment recommendations.`,
    category: "Healthcare",
    date: "December 15, 2023",
    image: "/images/project/Lmdx_healthcare.jpg",
    github: "#",
    demo: "https://luminamedix.com",
    tech: [
      "Python",
      "TensorFlow",
      "React",
      "Node.js",
      "MongoDB",
      "Socket.io",
      "DICOM",
      "HL7 FHIR",
    ],
    features: [
      "Medical Image Analysis",
      "Predictive Health Analytics",
      "Patient Data Management",
      "Real-time Monitoring",
      "Treatment Planning",
      "Emergency Response",
    ],
    challenges: [
      "Ensuring HIPAA compliance",
      "Processing complex medical data",
      "Managing real-time alerts",
      "Integrating with existing systems",
      "Handling sensitive information",
    ],
    solutions: [
      "Implemented secure architecture",
      "Created specialized processing pipeline",
      "Developed alert system",
      "Built integration framework",
      "Enhanced security measures",
    ],
    metrics: [
      { label: "Diagnosis Accuracy", value: "97%" },
      { label: "Response Time", value: "<2s" },
      { label: "Data Security", value: "100%" },
      { label: "Patient Satisfaction", value: "95%" },
    ],
    teamSize: "3 developers",
    duration: "5 months",
    nextSteps: [
      "Enhanced AI Diagnostics",
      "Mobile App Development",
      "Telemedicine Integration",
      "Research Tools",
    ],
  },
  {
    id: "arcsuono",
    title: "ArcSuono – AI Podcast & Audiobook Studio",
    description:
      "AI-powered podcast and audiobook creation platform. Generate complete episodes with AI narration, scripts, and cover art, or upload your own content.",
    longDescription: `ArcSuono revolutionizes podcast and audiobook creation by combining AI-driven content generation with professional production tools. Users can either create their own podcasts or leverage AI to generate complete episodes from topic prompts, including automatic script writing, professional narration, and cover art generation.

The platform features smart categorization, AI-powered discovery recommendations, and support for both user-created and AI-generated content. A unified library system helps users browse, organize, and manage podcasts and audiobooks seamlessly.`,
    category: "AI/Media",
    date: "December 1, 2024",
    image: "/images/project/arcsuono.png",
    github: "https://github.com/yourusername/arcsuono",
    demo: "https://arcsuono.app",
    tech: [
      "Next.js",
      "React",
      "Node.js",
      "Google Gemini API",
      "Text-to-Speech",
      "Audio Processing",
      "Cloud Storage",
      "MongoDB",
    ],
    features: [
      "AI Episode Generation",
      "Automatic Script Writing",
      "Professional Text-to-Speech",
      "AI Cover Art Generation",
      "Content Upload & Management",
      "Smart Discovery & Recommendations",
      "User & AI Content Library",
      "Playlist Support",
    ],
    challenges: [
      "High-quality audio generation and processing",
      "Scaling AI content generation",
      "Managing large media files efficiently",
      "Ensuring consistent audio quality",
      "Implementing intelligent discovery algorithm",
    ],
    solutions: [
      "Implemented robust audio processing pipeline",
      "Developed scalable backend architecture",
      "Used cloud storage with CDN",
      "Created quality assurance framework",
      "Built AI-powered recommendation engine",
    ],
    metrics: [
      { label: "Content Generated", value: "1000+" },
      { label: "Audio Quality", value: "HD 128kbps" },
      { label: "Generation Time", value: "<30min" },
      { label: "User Satisfaction", value: "92%" },
    ],
    teamSize: "2 developers",
    duration: "3 months",
    nextSteps: [
      "Mobile App Launch",
      "Advanced Voice Cloning",
      "Multi-language Support",
      "Monetization Features",
    ],
  },
  {
    id: "arcnia",
    title: "ArcNia – Smart Home with AI Assistant",
    description:
      "Intelligent smart home platform with device control, real-time monitoring, and conversational AI assistant for seamless home automation.",
    longDescription: `ArcNia transforms home automation through natural language control and intelligent device management. Users can add and manage their own IoT devices (lights, sensors, locks, thermostats) and control them via chat or voice commands.

The platform features a conversational AI assistant that understands context and intent, allowing users to ask natural questions like "Is the window open?" or "Turn on the bedroom lights." Real-time weather integration, security status monitoring, and sophisticated routine automation complete the ecosystem.`,
    category: "IoT/Smart Home",
    date: "November 15, 2024",
    image: "/images/project/arcnia.png",
    github: "https://github.com/yourusername/arcnia",
    demo: "https://arcnia.app",
    tech: [
      "Next.js",
      "React",
      "Node.js",
      "Google Gemini API",
      "MQTT",
      "WebSocket",
      "MongoDB",
      "OpenWeather API",
    ],
    features: [
      "Device Management & Control",
      "Conversational AI Assistant",
      "Real-time Device Status",
      "Weather Integration",
      "Security Monitoring",
      "Routine Automation",
      "Voice & Chat Control",
      "Real-time Notifications",
    ],
    challenges: [
      "Real-time device synchronization",
      "Natural language understanding for smart home commands",
      "Managing multiple device types and protocols",
      "Ensuring reliable automation execution",
      "Security and privacy for home automation",
    ],
    solutions: [
      "Implemented WebSocket for real-time updates",
      "Integrated advanced NLU models",
      "Built universal device abstraction layer",
      "Created robust automation engine",
      "Enhanced encryption and access controls",
    ],
    metrics: [
      { label: "Connected Devices", value: "500+" },
      { label: "Command Success Rate", value: "99.2%" },
      { label: "Response Time", value: "<500ms" },
      { label: "User Satisfaction", value: "94%" },
    ],
    teamSize: "3 developers",
    duration: "4 months",
    nextSteps: [
      "Voice Assistant Enhancement",
      "Mobile App",
      "Energy Analytics",
      "Predictive Automation",
    ],
  },
  {
    id: "arccinema",
    title: "ArcCinema – AI-Powered Movie & TV Platform",
    description:
      "Intelligent movie and TV recommendation platform with mood-based search, AI spoiler mode, and personalized content discovery.",
    longDescription: `ArcCinema revolutionizes entertainment discovery through advanced AI recommendations and personalized user experiences. The platform analyzes user mood, genre preferences, and viewing history to deliver highly relevant movie and TV show recommendations.

Features include smart mood-based search, an innovative AI Spoiler Mode for users who want detailed plot information before watching, comprehensive watchlist management, and real-time access to ratings, reviews, trailers, and upcoming releases. Fully responsive design works seamlessly on web and mobile devices.`,
    category: "Entertainment/AI",
    date: "October 20, 2024",
    image: "/images/project/arccinema.png",
    github: "https://github.com/yourusername/arccinema",
    demo: "https://arccinema.app",
    tech: [
      "Next.js",
      "React",
      "Node.js",
      "Google Gemini API",
      "TMDb API",
      "MongoDB",
      "Redis",
      "Responsive Design",
    ],
    features: [
      "AI-Powered Recommendations",
      "Mood-Based Search",
      "AI Spoiler Mode",
      "Watchlist Management",
      "Ratings & Reviews",
      "Trailer Integration",
      "Upcoming Releases",
      "Responsive Web & Mobile",
    ],
    challenges: [
      "Building accurate recommendation algorithm",
      "Integrating multiple data sources",
      "Handling large content datasets",
      "Ensuring responsive performance",
      "Managing user preferences at scale",
    ],
    solutions: [
      "Implemented collaborative filtering + content-based AI",
      "Built robust API aggregation layer",
      "Used caching and indexing strategies",
      "Optimized frontend performance",
      "Created scalable preference storage",
    ],
    metrics: [
      { label: "Recommendation Accuracy", value: "88%" },
      { label: "Content Library", value: "50k+ titles" },
      { label: "Page Load Time", value: "<1.5s" },
      { label: "User Engagement", value: "91%" },
    ],
    teamSize: "2 developers",
    duration: "3 months",
    nextSteps: [
      "Social Features",
      "Watch Party Feature",
      "Advanced Analytics",
      "Native Mobile Apps",
    ],
  },
  {
    id: "living-the-verse",
    title: "Living the Verse – AI Bible & Faith Platform",
    description:
      "Comprehensive Bible exploration platform with 1000+ verses, AI-powered explanations, spiritual guidance, and personalized faith journeys.",
    longDescription: `Living the Verse is a revolutionary faith-based platform that combines comprehensive Biblical content with advanced AI assistance. Users can explore over 1000 Bible verses with AI-generated reflections, prayer prompts, and practical life applications.

The platform features personalized faith journeys, verse bookmarking systems, and daily devotionals tailored to individual spiritual goals. Each verse includes contextual explanations, thematic connections, and AI-powered spiritual guidance to deepen understanding and encourage spiritual growth.`,
    category: "Faith/Education",
    date: "September 25, 2024",
    image: "/images/project/Living_the_Verse.png",
    github: "https://github.com/yourusername/living-the-verse",
    demo: "https://livingtheverse.app",
    tech: [
      "Next.js",
      "React",
      "Node.js",
      "Google Gemini API",
      "Bible API",
      "MongoDB",
      "TailwindCSS",
      "Framer Motion",
    ],
    features: [
      "1000+ Bible Verses Database",
      "AI-Powered Reflections",
      "Prayer Prompts & Guidance",
      "Life Application Insights",
      "Verse Bookmarking",
      "Daily Devotionals",
      "Personal Faith Journeys",
      "Thematic Collections",
    ],
    challenges: [
      "Managing large Biblical content database",
      "Creating contextually appropriate AI reflections",
      "Personalizing spiritual guidance",
      "Ensuring theological accuracy",
      "Building engaging learning experience",
    ],
    solutions: [
      "Implemented comprehensive verse database with metadata",
      "Developed faith-specific AI prompting",
      "Built personal journey tracking system",
      "Created theological review process",
      "Designed interactive learning interface",
    ],
    metrics: [
      { label: "Active Users", value: "5k+" },
      { label: "Verses Explored", value: "1000+" },
      { label: "Daily Devotional Completion", value: "76%" },
      { label: "User Satisfaction", value: "96%" },
    ],
    teamSize: "2 developers",
    duration: "5 months",
    nextSteps: [
      "Community Features",
      "Mobile App Launch",
      "Multi-language Support",
      "Offline Mode",
      "Bible Study Groups",
    ],
  },
];

export type Project = (typeof projects)[number];
